### ISSUE TITLE
Just a Note : Pymodbus for python3 is officially supported

### ISSUE THREAD

**Issue by dhoomakethu** [uzumaxy/pymodbus3#7]
A universal distribution for python 2 and 3 is available on PIP [pymodbus-13.0rc2](https://pypi.python.org/pypi/pymodbus/1.3.0rc2)

Also note, it is also being supported on the official pymodbus repo [pymodbus](https://github.com/riptideio/pymodbus)

@uzumaxy If you think there is anything really missing from the official repo and required to go in there, could you please raise a PR

**Comment by eterey** [comment]
Hey @dhoomakethu that's great!

I thinks my repo can be closed now.

Thanks!
