### ISSUE TITLE
How to uninstall pymodbus3?

### ISSUE THREAD

**Issue by Gim6626** [uzumaxy/pymodbus3#8]
Faced same issue as in https://github.com/uzumaxy/pymodbus3/issues/3 , installed pymodbus3 using `sudo python3 setup.py install` from git clone dir and now I wonder how to uninstall it? `sudo python3 setup.py uninstall` returns "error: invalid command 'uninstall'". For comparison. pip has such function, and I could successfully remove old version of pymodbus3 that exists in pip repo.

**Comment by kierun** [comment]
Try: `sudo pip uninstall pymodbus3` as it should work.

**Comment by shobha-maurya** [comment]
no it's not working
