### ISSUE TITLE
Modbus serial sync server

### ISSUE THREAD

**Issue by tomkcook** [uzumaxy/pymodbus3#9]
I've just tried instantiating a Modbus RTU serial synchronous server.  It seems that the classes in `pymodbus3/server/sync.py` expect a `serial.Serial` object to have the same API as a socket - ie. to have `send` and `recv` methods, while what it actually has are `read` and `write` methods.

Am I missing something?

**Comment by eterey** [comment]
Pull-request has been merged and issue should be solved now. Feel free to re-open it in case of any issues.
Thanks for your contribution!
